
import React, { useState, useEffect } from 'react';
import { QUESTIONS } from '../data';
import { AlertCircle, ArrowRight, RotateCcw, Printer, Award, Info, X } from 'lucide-react';

export const ToolAssessment = () => {
  const [answers, setAnswers] = useState<Record<number, number>>({});
  const [showResult, setShowResult] = useState(false);
  const [isPrintMode, setIsPrintMode] = useState(false);
  const [activeInfo, setActiveInfo] = useState<number | null>(null);

  // Load from local storage on mount
  useEffect(() => {
    const saved = localStorage.getItem('assessment_answers');
    if (saved) {
      setAnswers(JSON.parse(saved));
    }
  }, []);

  // Save to local storage on change
  useEffect(() => {
    localStorage.setItem('assessment_answers', JSON.stringify(answers));
  }, [answers]);

  const handleSelect = (questionId: number, score: number) => {
    setAnswers(prev => ({ ...prev, [questionId]: score }));
  };

  const calculateScore = () => {
    const totalScore = (Object.values(answers) as number[]).reduce((a, b) => a + b, 0);
    const maxScore = QUESTIONS.length * 5;
    const percentage = (totalScore / maxScore) * 100;
    return { totalScore, percentage };
  };

  const getResult = (percentage: number) => {
    if (percentage < 15) return {
      rating: "⭐⭐⭐⭐⭐ Excellent",
      color: "text-green-600",
      bg: "bg-green-50",
      border: "border-green-200",
      title: "Low Risk",
      desc: "Your home electrical system appears to be in great condition. Maintain your regular checks."
    };
    if (percentage < 35) return {
      rating: "⭐⭐⭐ Fair",
      color: "text-yellow-600",
      bg: "bg-yellow-50",
      border: "border-yellow-200",
      title: "Moderate Risk",
      desc: "There are some warning signs. Review the questions where you answered 'Yes' and address those issues soon."
    };
    return {
      rating: "⭐ Critical",
      color: "text-red-600",
      bg: "bg-red-50",
      border: "border-red-200",
      title: "High Risk",
      desc: "Significant hazards detected. We strongly recommend consulting a certified electrician immediately."
    };
  };

  const { percentage, totalScore } = calculateScore();
  const resultData = getResult(percentage);
  const isComplete = Object.keys(answers).length === QUESTIONS.length;
  const isPerfect = totalScore === 0 && isComplete;

  const handlePrint = () => {
    setIsPrintMode(true);
    setTimeout(() => {
      window.print();
      setIsPrintMode(false);
    }, 100);
  };

  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      {/* Print Header - Only Visible when printing */}
      <div className="hidden print-only mb-8 border-b-2 border-gray-800 pb-4">
        <h1 className="text-3xl font-bold">Home Electrical Safety Audit</h1>
        <p className="text-gray-600">Generated by ElectroSafe.homes</p>
        <p className="text-sm mt-2">Date: {new Date().toLocaleDateString()}</p>
      </div>

      <div className="text-center mb-10 no-print">
        <h1 className="text-3xl font-bold text-gray-900">Home Electrical Safety Assessment</h1>
        <p className="mt-2 text-gray-600">Answer these {QUESTIONS.length} questions to get your safety rating. Your progress is saved automatically.</p>
      </div>

      {!showResult ? (
        <div className="space-y-8">
          {QUESTIONS.map((q, idx) => (
            <div key={q.id} className="bg-white p-6 rounded-lg shadow-sm border border-gray-200 print:border-none print:p-0 print:mb-4 relative">
              <div className="flex justify-between items-start mb-4">
                <p className="font-medium text-lg text-gray-800 pr-8">
                  <span className="text-blue-500 font-bold mr-2">{idx + 1}.</span>
                  {q.question}
                </p>
                <button 
                  onClick={() => setActiveInfo(activeInfo === q.id ? null : q.id)}
                  className="text-gray-400 hover:text-blue-600 transition-colors p-1"
                  title="Why we ask this"
                >
                  {activeInfo === q.id ? <X className="w-5 h-5" /> : <Info className="w-5 h-5" />}
                </button>
              </div>

              {/* Educational Context */}
              {activeInfo === q.id && (
                <div className="bg-blue-50 border-l-4 border-blue-500 p-4 mb-4 rounded-r-lg animate-in fade-in slide-in-from-top-2">
                  <h4 className="text-xs font-bold text-blue-600 uppercase tracking-wide mb-1">Why this matters</h4>
                  <p className="text-sm text-blue-900">{q.whyItMatters}</p>
                </div>
              )}

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                {q.options.map((opt) => (
                  <button
                    key={opt.label}
                    onClick={() => handleSelect(q.id, opt.score)}
                    className={`px-4 py-3 rounded-md text-left text-sm font-medium transition-all duration-200 border ${
                      answers[q.id] === opt.score
                        ? 'bg-blue-600 text-white border-blue-600 ring-2 ring-blue-200'
                        : 'bg-gray-50 text-gray-700 border-gray-200 hover:bg-gray-100'
                    }`}
                  >
                    {opt.label}
                  </button>
                ))}
              </div>
            </div>
          ))}

          <div className="sticky bottom-4 bg-white/90 backdrop-blur p-4 rounded-lg shadow-lg border-t border-gray-200 flex justify-between items-center no-print">
            <div className="text-sm font-medium text-gray-500">
              {Object.keys(answers).length} of {QUESTIONS.length} answered
            </div>
            <button
              disabled={!isComplete}
              onClick={() => setShowResult(true)}
              className={`flex items-center gap-2 px-6 py-3 rounded-lg font-bold text-white transition-colors ${
                isComplete ? 'bg-green-600 hover:bg-green-700 shadow-md' : 'bg-gray-300 cursor-not-allowed'
              }`}
            >
              Analyze Results <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      ) : (
        <div className={`p-8 rounded-xl border-2 ${resultData.bg} ${resultData.border}`}>
          <div className="text-center">
            
            {/* GAMIFICATION: Perfect Score Badge */}
            {isPerfect && (
              <div className="mb-6 animate-pulse">
                 <div className="inline-flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-yellow-400 to-yellow-500 text-white rounded-full font-bold shadow-lg transform hover:scale-105 transition-transform">
                   <Award className="w-6 h-6" /> ElectroSafe Certified Safe
                 </div>
                 <p className="text-xs text-yellow-700 font-bold mt-2 uppercase tracking-wide">You aced the audit!</p>
              </div>
            )}

            <h2 className={`text-4xl font-bold mb-2 ${resultData.color}`}>{resultData.rating}</h2>
            <h3 className="text-2xl font-semibold text-gray-800 mb-4">{resultData.title}</h3>
            <p className="text-gray-700 mb-8 max-w-lg mx-auto">{resultData.desc}</p>
            
            <div className="bg-white p-6 rounded-lg shadow-sm mb-8 text-left border border-gray-100">
              <h4 className="font-bold text-gray-900 mb-4 flex items-center gap-2">
                <AlertCircle className="w-5 h-5 text-blue-600" />
                Recommended Actions
              </h4>
              <ul className="space-y-3 text-sm text-gray-600">
                {isPerfect && <li className="text-green-600 font-medium">✓ Maintain your excellent habits. Re-test annually.</li>}
                {percentage > 10 && <li>• Check all smoke detectors and replace batteries.</li>}
                {percentage > 25 && <li>• Inspect extension cords and replace any that show wear.</li>}
                {percentage > 40 && <li>• Test all GFCI/RCD buttons to ensure protection is active.</li>}
                {percentage > 60 && <li className="font-bold text-red-600">• Schedule an inspection with a professional electrician immediately.</li>}
                <li>• Download our room-by-room checklist for a deeper audit.</li>
              </ul>
            </div>

            <div className="flex flex-col sm:flex-row gap-4 justify-center no-print">
               <button
                onClick={handlePrint}
                className="flex items-center gap-2 px-6 py-3 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition shadow-sm font-bold"
              >
                <Printer className="w-4 h-4" /> Print Official Report
              </button>
              <button
                onClick={() => {
                  if(window.confirm("This will clear your saved progress. Are you sure?")) {
                    setShowResult(false);
                    setAnswers({});
                    localStorage.removeItem('assessment_answers');
                    window.scrollTo(0, 0);
                  }
                }}
                className="flex items-center gap-2 px-6 py-3 bg-gray-200 text-gray-700 rounded-md hover:bg-gray-300 transition"
              >
                <RotateCcw className="w-4 h-4" /> Clear & Start Over
              </button>
            </div>
          </div>

          {/* Detailed Breakdown for Print Only */}
          <div className="hidden print-only mt-8 text-left">
             <h4 className="font-bold text-lg border-b border-gray-300 pb-2 mb-4">Detailed Audit Log</h4>
             <table className="w-full text-sm">
               <thead>
                 <tr className="bg-gray-100">
                   <th className="text-left p-2">Category / Question</th>
                   <th className="text-right p-2">Score</th>
                 </tr>
               </thead>
               <tbody>
                 {QUESTIONS.map(q => {
                   const score = answers[q.id];
                   // Only show issues (score > 0) to save paper
                   if (score > 0) {
                     return (
                        <tr key={q.id} className="border-b border-gray-200">
                          <td className="p-2">
                            <div className="font-medium">{q.question}</div>
                            <div className="text-xs text-red-600">{q.options.find(o => o.score === score)?.label}</div>
                          </td>
                          <td className="text-right p-2 font-bold text-red-600">+{score}</td>
                        </tr>
                     );
                   }
                   return null;
                 })}
               </tbody>
             </table>
             <div className="mt-4 text-right font-bold">Total Risk Score: {totalScore} / {QUESTIONS.length * 5}</div>
          </div>
        </div>
      )}
    </div>
  );
};
